"use client";
import { useState, useEffect } from "react";
import { useAuth } from "@/context/AuthContext";
import api from "@/lib/axios";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import { Sparkles, Loader2, BrainCircuit, Download } from "lucide-react";
import Link from "next/link";

export default function ReportPage() {
  const { user } = useAuth();
  const [reportContent, setReportContent] = useState<string>("");
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const fetchReport = async () => {
      try {
        const res = await api.get("/analytics/ai-report");
        setReportContent(res.data);
      } catch (err) {
        console.error(err);
        setError(
          "Unable to generate the AI report at this time. Please try again later.",
        );
      } finally {
        setLoading(false);
      }
    };

    if (user) {
      fetchReport();
    }
  }, [user]);

  if (loading) {
    return (
      <div className="flex flex-col items-center justify-center min-h-[60vh] text-center">
        <div className="relative mb-6">
          <div className="absolute inset-0 bg-primary/20 rounded-full blur-xl animate-pulse"></div>
          <BrainCircuit className="h-20 w-20 text-primary relative z-10 animate-bounce" />
        </div>
        <h2 className="text-2xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-primary to-indigo-600 mb-2">
          Analyzing Your Progress
        </h2>
        <p className="text-muted-foreground max-w-md flex items-center gap-2">
          <Loader2 className="h-4 w-4 animate-spin" />
          Gemini AI is reviewing your recent sessions, scores, and gamification
          stats...
        </p>
      </div>
    );
  }

  if (error) {
    return (
      <div className="max-w-4xl mx-auto py-12 px-4 sm:px-6">
        <div className="bg-destructive/10 border border-destructive/20 rounded-lg p-6 text-center">
          <h2 className="text-lg font-semibold text-destructive mb-2">Oops!</h2>
          <p className="text-destructive/80 mb-4">{error}</p>
          <Link
            href="/dashboard"
            className="text-primary hover:underline font-medium"
          >
            Return to Dashboard
          </Link>
        </div>
      </div>
    );
  }

  return (
    <div className="max-w-5xl mx-auto py-8 px-4 sm:px-6 lg:px-8">
      <div className="flex items-center gap-3 mb-8">
        <div className="p-3 bg-primary/10 rounded-xl">
          <Sparkles className="h-8 w-8 text-primary" />
        </div>
        <div>
          <h1 className="text-3xl font-bold text-foreground">
            AI Progress Report
          </h1>
          <p className="text-muted-foreground">
            Personalized insights and study plan generated by Gemini
          </p>
        </div>
      </div>

      <div className="bg-card rounded-2xl shadow-xl border border-border overflow-hidden">
        <div className="bg-gradient-to-r from-primary/10 via-background to-background border-b border-border p-6 flex justify-between items-center">
          <span className="text-sm font-medium text-muted-foreground">
            Generated on {new Date().toLocaleDateString()}
          </span>
          <div className="flex items-center gap-3">
            <span className="px-3 py-1 bg-primary/20 text-primary text-xs font-bold rounded-full uppercase tracking-wider">
              Powered by Gemini AI
            </span>
            <button
              onClick={() => window.print()}
              className="print:hidden flex items-center gap-1.5 px-3 py-1.5 bg-card border border-border rounded-xl text-xs font-semibold hover:bg-muted transition-colors"
            >
              <Download className="h-3.5 w-3.5" />
              Download PDF
            </button>
          </div>
        </div>
        <div className="p-8 prose prose-indigo max-w-none prose-h1:text-2xl prose-h1:font-bold prose-h1:border-b prose-h1:pb-2 prose-h2:text-xl prose-h2:text-primary prose-a:text-primary">
          <ReactMarkdown remarkPlugins={[remarkGfm]}>
            {reportContent}
          </ReactMarkdown>
        </div>
      </div>
    </div>
  );
}
