import {
  BadRequestException,
  Injectable,
  NotFoundException,
} from '@nestjs/common';
import { PrismaService } from '../../prisma/prisma.service';
import {
  ImprovementProposalDto,
  ImprovementStatus,
} from './improvement.types';

/**
 * Deterministically detects whether a metric has regressed beyond a tolerance threshold.
 */
export function detectRegression(
  baseline: number,
  current: number,
  threshold: number,
): boolean {
  if (baseline === 0) {
    return current !== 0;
  }

  const change = Math.abs(current - baseline) / Math.abs(baseline);
  return change >= threshold;
}

/**
 * Validates mandatory safety, privacy, and teacher review gates before an experiment can launch.
 */
export function canStartExperiment(input: {
  riskLevel: string;
  safetyReviewed: boolean;
  teacherReviewed: boolean;
  privacyReviewed: boolean;
}): boolean {
  if (!input.safetyReviewed) {
    return false;
  }

  if (!input.privacyReviewed) {
    return false;
  }

  if (input.riskLevel !== 'LOW' && !input.teacherReviewed) {
    return false;
  }

  return true;
}

@Injectable()
export class ImprovementService {
  constructor(private readonly prisma: PrismaService) {}

  /**
   * Submit an improvement proposal generated by analytics, teachers, AI, or research.
   */
  async createProposal(dto: ImprovementProposalDto) {
    const prismaClient = this.prisma as any;
    return prismaClient.improvementProposal.create({
      data: {
        tenantId: dto.tenantId,
        source: dto.source,
        title: dto.title,
        description: dto.description,
        hypothesis: dto.hypothesis,
        expectedOutcome: dto.expectedOutcome,
        riskLevel: dto.riskLevel,
        status: dto.riskLevel === 'LOW' ? ImprovementStatus.PROPOSED : ImprovementStatus.APPROVAL_REQUIRED,
        affectedSystems: JSON.stringify(dto.affectedSystems),
        rollbackPlan: dto.rollbackPlan,
        proposedBy: dto.proposedBy,
      },
    });
  }

  /**
   * Get single proposal by ID.
   */
  async getProposal(id: string) {
    const prismaClient = this.prisma as any;
    const proposal = await prismaClient.improvementProposal.findUnique({
      where: { id },
    });
    if (!proposal) {
      throw new NotFoundException(`Improvement proposal '${id}' not found`);
    }
    return proposal;
  }

  /**
   * Human/Governance approval of an improvement proposal.
   */
  async approveProposal(id: string, approvedBy: string) {
    const proposal = await this.getProposal(id);
    const prismaClient = this.prisma as any;

    return prismaClient.improvementProposal.update({
      where: { id },
      data: {
        status: ImprovementStatus.APPROVED,
        approvedBy,
        approvedAt: new Date(),
      },
    });
  }

  /**
   * Rejection of an improvement proposal.
   */
  async rejectProposal(id: string, rejectedBy: string, reason: string) {
    const proposal = await this.getProposal(id);
    const prismaClient = this.prisma as any;

    return prismaClient.improvementProposal.update({
      where: { id },
      data: {
        status: ImprovementStatus.REJECTED,
        approvedBy: rejectedBy,
        completedAt: new Date(),
      },
    });
  }

  /**
   * List improvement proposals with filters.
   */
  async listProposals(filters: { status?: string; tenantId?: string; limit?: number }) {
    const prismaClient = this.prisma as any;
    const where: any = {};
    if (filters.status) where.status = filters.status;
    if (filters.tenantId) where.tenantId = filters.tenantId;

    return prismaClient.improvementProposal.findMany({
      where,
      orderBy: { createdAt: 'desc' },
      take: filters.limit ?? 50,
    });
  }

  /**
   * Register or evaluate experiment governance.
   */
  async evaluateExperimentGate(experimentId: string, riskLevel: string) {
    const prismaClient = this.prisma as any;
    let gov = await prismaClient.experimentGovernance.findUnique({
      where: { experimentId },
    });

    if (!gov) {
      gov = await prismaClient.experimentGovernance.create({
        data: {
          experimentId,
          riskLevel,
        },
      });
    }

    const canStart = canStartExperiment({
      riskLevel: gov.riskLevel,
      safetyReviewed: gov.safetyReviewed,
      teacherReviewed: gov.teacherReviewed,
      privacyReviewed: gov.privacyReviewed,
    });

    return {
      experimentId,
      governance: gov,
      canStart,
    };
  }
}
